/**
 * IFJ Project 2020: Team 008, variant II
 *
 * @file builtin.c
 *
 * @brief Built-in structure method definitions.
 *
 *
 * @author Martin Kneslík <xknesl02@stud.fit.vutbr.cz>
 * @author Adriana Jurkechová <xjurke02@stud.fit.vutbr.cz>
 * @author Karel Norek <xnorek01@stud.fit.vutbr.cz>
 * @author Petr Salaba <xsalab00@stud.fit.vutbr.cz>
 */

#include "builtin.h"
#include "generator.h"

/**
 * @brief Initialize list of builtin functions
 *
 * @param list Allocated builtin list
 */
void builtinInit(Builtin_list *list) {
    list->head = NULL;
}

/**
 * @brief Free a builtin list, does not free the pointer itself
 *
 * @param list The builtin list
 */
void builtinFree(Builtin_list *list) {
    if (!list || !list->head)
        return;
    Builtin *item = list->head;
    Builtin *tmp;
    while (item) {
        tmp = item->next;
        strFree(item->name);
        free(item->name);
        strFree(item->content);
        free(item->content);
        free(item);
        item = tmp;
    }
}

/**
 * @brief Add a new builtin function to the list
 *
 * @param list The builtin list
 * @param name Real name of the builtin function, used in LABEL
 * @param content Content of the builtin function - list of IFJcode20 instructions
 * @param malformed_name Name generated by the generator to identify future calls
 * @return Exit code (0 = success)
 */
int addBuiltin(Builtin_list *list, const char *name, const char *content, string *malformed_name) {
    if (!list || !name || !content)
        return 1;
    Builtin *item = malloc(sizeof(Builtin));
    item->used = false;
    item->next = list->head;
    item->malformed_name = malformed_name;
    if (!(item->name = strCreate(name))) {
        strFree(item->malformed_name);
        free(item->malformed_name);
        free(item);
        return 1;
    }
    if (!(item->content = strCreate(content))) {
        strFree(item->malformed_name);
        free(item->malformed_name);
        strFree(item->name);
        free(item->name);
        free(item);
        return 1;
    }
    list->head = item;
    return 0;
}

/**
 * @brief Tries to find a builtin function of the specified malformed name
 *
 * @param list The builtin list
 * @param name Malformed name
 * @return Builtin function if found, otherwise NULL
 */
Builtin *getBuiltin(Builtin_list *list, string *name) {
    if (!list || !name)
        return NULL;
    for (Builtin *item = list->head; item; item = item->next)
        if (!strCmpString(name, item->malformed_name))
            return item;
    return NULL;
}
